<?php

namespace Database\Seeders;

use App\Models\PpaFundingSource;
use App\Models\FundingSource;
use Illuminate\Database\Seeder;

class PpaFundingSourceSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $codeMap = [
            'GF-Proper' => 'GF Proper',
            '5% GAD' => 'GF-5% GAD',
        ];

        $fundingSources = FundingSource::pluck('id', 'code');

        $ppaFundingSources = [
            [
                'id' => 1,
                'aip_entry_id' => 1,
                'funding_source_id' => 'GF-Proper',
                'ps_amount' => 39000,
                'mooe_amount' => null,
                'fe_amount' => null,
                'co_amount' => null,
                'ccet_adaptation' => null,
                'ccet_mitigation' => null,
                'cc_typology_id' => null,
            ],
            [
                'id' => 2,
                'aip_entry_id' => 2,
                'funding_source_id' => null,
                'ps_amount' => null,
                'mooe_amount' => null,
                'fe_amount' => null,
                'co_amount' => null,
                'ccet_adaptation' => null,
                'ccet_mitigation' => null,
                'cc_typology_id' => null,
            ],
            [
                'id' => 3,
                'aip_entry_id' => 3,
                'funding_source_id' => null,
                'ps_amount' => null,
                'mooe_amount' => null,
                'fe_amount' => null,
                'co_amount' => null,
                'ccet_adaptation' => null,
                'ccet_mitigation' => null,
                'cc_typology_id' => null,
            ],
            [
                'id' => 4,
                'aip_entry_id' => 4,
                'funding_source_id' => 'GF-Proper',
                'ps_amount' => null,
                'mooe_amount' => 420,
                'fe_amount' => null,
                'co_amount' => null,
                'ccet_adaptation' => null,
                'ccet_mitigation' => null,
                'cc_typology_id' => null,
            ],
            [
                'id' => 5,
                'aip_entry_id' => 5,
                'funding_source_id' => 'GF-Proper',
                'ps_amount' => null,
                'mooe_amount' => 490,
                'fe_amount' => null,
                'co_amount' => null,
                'ccet_adaptation' => null,
                'ccet_mitigation' => null,
                'cc_typology_id' => null,
            ],
            [
                'id' => 6,
                'aip_entry_id' => 6,
                'funding_source_id' => null,
                'ps_amount' => null,
                'mooe_amount' => null,
                'fe_amount' => null,
                'co_amount' => null,
                'ccet_adaptation' => null,
                'ccet_mitigation' => null,
                'cc_typology_id' => null,
            ],
            [
                'id' => 7,
                'aip_entry_id' => 7,
                'funding_source_id' => null,
                'ps_amount' => null,
                'mooe_amount' => null,
                'fe_amount' => null,
                'co_amount' => null,
                'ccet_adaptation' => null,
                'ccet_mitigation' => null,
                'cc_typology_id' => null,
            ],
            [
                'id' => 8,
                'aip_entry_id' => 8,
                'funding_source_id' => null,
                'ps_amount' => null,
                'mooe_amount' => null,
                'fe_amount' => null,
                'co_amount' => null,
                'ccet_adaptation' => null,
                'ccet_mitigation' => null,
                'cc_typology_id' => null,
            ],
            [
                'id' => 9,
                'aip_entry_id' => 9,
                'funding_source_id' => 'GF-Proper',
                'ps_amount' => null,
                'mooe_amount' => 1700,
                'fe_amount' => null,
                'co_amount' => null,
                'ccet_adaptation' => null,
                'ccet_mitigation' => null,
                'cc_typology_id' => null,
            ],
            [
                'id' => 10,
                'aip_entry_id' => 10,
                'funding_source_id' => null,
                'ps_amount' => null,
                'mooe_amount' => null,
                'fe_amount' => null,
                'co_amount' => null,
                'ccet_adaptation' => null,
                'ccet_mitigation' => null,
                'cc_typology_id' => null,
            ],
            [
                'id' => 11,
                'aip_entry_id' => 11,
                'funding_source_id' => null,
                'ps_amount' => null,
                'mooe_amount' => null,
                'fe_amount' => null,
                'co_amount' => null,
                'ccet_adaptation' => null,
                'ccet_mitigation' => null,
                'cc_typology_id' => null,
            ],
            [
                'id' => 12,
                'aip_entry_id' => 12,
                'funding_source_id' => 'GF-Proper',
                'ps_amount' => null,
                'mooe_amount' => 90,
                'fe_amount' => null,
                'co_amount' => null,
                'ccet_adaptation' => null,
                'ccet_mitigation' => null,
                'cc_typology_id' => null,
            ],
            [
                'id' => 13,
                'aip_entry_id' => 13,
                'funding_source_id' => 'GF-Proper',
                'ps_amount' => null,
                'mooe_amount' => 110,
                'fe_amount' => null,
                'co_amount' => null,
                'ccet_adaptation' => null,
                'ccet_mitigation' => null,
                'cc_typology_id' => null,
            ],
            [
                'id' => 14,
                'aip_entry_id' => 14,
                'funding_source_id' => 'GF-Proper',
                'ps_amount' => null,
                'mooe_amount' => 2000,
                'fe_amount' => null,
                'co_amount' => null,
                'ccet_adaptation' => null,
                'ccet_mitigation' => null,
                'cc_typology_id' => null,
            ],
            [
                'id' => 15,
                'aip_entry_id' => 15,
                'funding_source_id' => 'GF-Proper',
                'ps_amount' => null,
                'mooe_amount' => 60,
                'fe_amount' => null,
                'co_amount' => null,
                'ccet_adaptation' => null,
                'ccet_mitigation' => null,
                'cc_typology_id' => null,
            ],
            [
                'id' => 16,
                'aip_entry_id' => 16,
                'funding_source_id' => 'GF-Proper',
                'ps_amount' => null,
                'mooe_amount' => 500,
                'fe_amount' => null,
                'co_amount' => null,
                'ccet_adaptation' => null,
                'ccet_mitigation' => null,
                'cc_typology_id' => null,
            ],
            [
                'id' => 17,
                'aip_entry_id' => 17,
                'funding_source_id' => 'GF-Proper',
                'ps_amount' => null,
                'mooe_amount' => 200,
                'fe_amount' => null,
                'co_amount' => null,
                'ccet_adaptation' => null,
                'ccet_mitigation' => null,
                'cc_typology_id' => null,
            ],
            [
                'id' => 18,
                'aip_entry_id' => 18,
                'funding_source_id' => 'GF-Proper',
                'ps_amount' => null,
                'mooe_amount' => 1800,
                'fe_amount' => null,
                'co_amount' => null,
                'ccet_adaptation' => null,
                'ccet_mitigation' => null,
                'cc_typology_id' => null,
            ],
            [
                'id' => 19,
                'aip_entry_id' => 19,
                'funding_source_id' => 'GF-Proper',
                'ps_amount' => null,
                'mooe_amount' => 4500,
                'fe_amount' => null,
                'co_amount' => null,
                'ccet_adaptation' => null,
                'ccet_mitigation' => null,
                'cc_typology_id' => null,
            ],
            [
                'id' => 20,
                'aip_entry_id' => 20,
                'funding_source_id' => null,
                'ps_amount' => null,
                'mooe_amount' => null,
                'fe_amount' => null,
                'co_amount' => null,
                'ccet_adaptation' => null,
                'ccet_mitigation' => null,
                'cc_typology_id' => null,
            ],
            [
                'id' => 21,
                'aip_entry_id' => 21,
                'funding_source_id' => null,
                'ps_amount' => null,
                'mooe_amount' => null,
                'fe_amount' => null,
                'co_amount' => null,
                'ccet_adaptation' => null,
                'ccet_mitigation' => null,
                'cc_typology_id' => null,
            ],
            [
                'id' => 22,
                'aip_entry_id' => 22,
                'funding_source_id' => 'GF-Proper',
                'ps_amount' => null,
                'mooe_amount' => 10,
                'fe_amount' => null,
                'co_amount' => null,
                'ccet_adaptation' => null,
                'ccet_mitigation' => null,
                'cc_typology_id' => null,
            ],
            [
                'id' => 23,
                'aip_entry_id' => 23,
                'funding_source_id' => 'GF-Proper',
                'ps_amount' => null,
                'mooe_amount' => 900,
                'fe_amount' => null,
                'co_amount' => null,
                'ccet_adaptation' => null,
                'ccet_mitigation' => null,
                'cc_typology_id' => null,
            ],
            [
                'id' => 24,
                'aip_entry_id' => 24,
                'funding_source_id' => 'GF-Proper',
                'ps_amount' => null,
                'mooe_amount' => 70,
                'fe_amount' => null,
                'co_amount' => null,
                'ccet_adaptation' => null,
                'ccet_mitigation' => null,
                'cc_typology_id' => null,
            ],
            [
                'id' => 25,
                'aip_entry_id' => 25,
                'funding_source_id' => 'GF-Proper',
                'ps_amount' => null,
                'mooe_amount' => 10,
                'fe_amount' => null,
                'co_amount' => null,
                'ccet_adaptation' => null,
                'ccet_mitigation' => null,
                'cc_typology_id' => null,
            ],
            [
                'id' => 26,
                'aip_entry_id' => 26,
                'funding_source_id' => 'GF-Proper',
                'ps_amount' => null,
                'mooe_amount' => 35,
                'fe_amount' => null,
                'co_amount' => null,
                'ccet_adaptation' => null,
                'ccet_mitigation' => null,
                'cc_typology_id' => null,
            ],
            [
                'id' => 27,
                'aip_entry_id' => 27,
                'funding_source_id' => 'GF-Proper',
                'ps_amount' => null,
                'mooe_amount' => 50,
                'fe_amount' => null,
                'co_amount' => null,
                'ccet_adaptation' => null,
                'ccet_mitigation' => null,
                'cc_typology_id' => null,
            ],
            [
                'id' => 28,
                'aip_entry_id' => 28,
                'funding_source_id' => null,
                'ps_amount' => null,
                'mooe_amount' => null,
                'fe_amount' => null,
                'co_amount' => null,
                'ccet_adaptation' => null,
                'ccet_mitigation' => null,
                'cc_typology_id' => null,
            ],
            [
                'id' => 29,
                'aip_entry_id' => 29,
                'funding_source_id' => 'GF-Proper',
                'ps_amount' => null,
                'mooe_amount' => 2600,
                'fe_amount' => null,
                'co_amount' => null,
                'ccet_adaptation' => null,
                'ccet_mitigation' => null,
                'cc_typology_id' => null,
            ],
            [
                'id' => 30,
                'aip_entry_id' => 30,
                'funding_source_id' => null,
                'ps_amount' => null,
                'mooe_amount' => null,
                'fe_amount' => null,
                'co_amount' => null,
                'ccet_adaptation' => null,
                'ccet_mitigation' => null,
                'cc_typology_id' => null,
            ],
            [
                'id' => 31,
                'aip_entry_id' => 31,
                'funding_source_id' => 'GF-Proper',
                'ps_amount' => null,
                'mooe_amount' => 4200,
                'fe_amount' => null,
                'co_amount' => 2000,
                'ccet_adaptation' => null,
                'ccet_mitigation' => null,
                'cc_typology_id' => null,
            ],
            [
                'id' => 32,
                'aip_entry_id' => 32,
                'funding_source_id' => 'GF-Proper',
                'ps_amount' => null,
                'mooe_amount' => 3800,
                'fe_amount' => null,
                'co_amount' => 4000,
                'ccet_adaptation' => null,
                'ccet_mitigation' => null,
                'cc_typology_id' => null,
            ],
            [
                'id' => 33,
                'aip_entry_id' => 33,
                'funding_source_id' => 'GF-Proper',
                'ps_amount' => null,
                'mooe_amount' => 3600,
                'fe_amount' => null,
                'co_amount' => null,
                'ccet_adaptation' => null,
                'ccet_mitigation' => null,
                'cc_typology_id' => null,
            ],
            [
                'id' => 34,
                'aip_entry_id' => 34,
                'funding_source_id' => 'GF-Proper',
                'ps_amount' => null,
                'mooe_amount' => 1000,
                'fe_amount' => null,
                'co_amount' => 40000,
                'ccet_adaptation' => null,
                'ccet_mitigation' => null,
                'cc_typology_id' => null,
            ],
            [
                'id' => 35,
                'aip_entry_id' => 35,
                'funding_source_id' => 'GF-Proper',
                'ps_amount' => null,
                'mooe_amount' => 100,
                'fe_amount' => null,
                'co_amount' => null,
                'ccet_adaptation' => null,
                'ccet_mitigation' => null,
                'cc_typology_id' => null,
            ],
            [
                'id' => 36,
                'aip_entry_id' => 36,
                'funding_source_id' => 'GF-Proper',
                'ps_amount' => null,
                'mooe_amount' => 2000,
                'fe_amount' => null,
                'co_amount' => null,
                'ccet_adaptation' => null,
                'ccet_mitigation' => null,
                'cc_typology_id' => null,
            ],
            [
                'id' => 37,
                'aip_entry_id' => 37,
                'funding_source_id' => 'GF-Proper',
                'ps_amount' => null,
                'mooe_amount' => 1800,
                'fe_amount' => null,
                'co_amount' => 4600,
                'ccet_adaptation' => null,
                'ccet_mitigation' => null,
                'cc_typology_id' => null,
            ],
            [
                'id' => 38,
                'aip_entry_id' => 38,
                'funding_source_id' => 'GF-Proper',
                'ps_amount' => null,
                'mooe_amount' => 1000,
                'fe_amount' => null,
                'co_amount' => null,
                'ccet_adaptation' => null,
                'ccet_mitigation' => null,
                'cc_typology_id' => null,
            ],
            [
                'id' => 39,
                'aip_entry_id' => 39,
                'funding_source_id' => 'GF-Proper',
                'ps_amount' => null,
                'mooe_amount' => null,
                'fe_amount' => null,
                'co_amount' => 70000,
                'ccet_adaptation' => null,
                'ccet_mitigation' => null,
                'cc_typology_id' => null,
            ],
            [
                'id' => 40,
                'aip_entry_id' => 40,
                'funding_source_id' => null,
                'ps_amount' => null,
                'mooe_amount' => null,
                'fe_amount' => null,
                'co_amount' => null,
                'ccet_adaptation' => null,
                'ccet_mitigation' => null,
                'cc_typology_id' => null,
            ],
            [
                'id' => 41,
                'aip_entry_id' => 41,
                'funding_source_id' => null,
                'ps_amount' => null,
                'mooe_amount' => null,
                'fe_amount' => null,
                'co_amount' => null,
                'ccet_adaptation' => null,
                'ccet_mitigation' => null,
                'cc_typology_id' => null,
            ],
            [
                'id' => 42,
                'aip_entry_id' => 42,
                'funding_source_id' => '5% GAD',
                'ps_amount' => null,
                'mooe_amount' => 150,
                'fe_amount' => null,
                'co_amount' => 1000,
                'ccet_adaptation' => null,
                'ccet_mitigation' => null,
                'cc_typology_id' => null,
            ],
            [
                'id' => 43,
                'aip_entry_id' => 43,
                'funding_source_id' => '5% GAD',
                'ps_amount' => null,
                'mooe_amount' => 150,
                'fe_amount' => null,
                'co_amount' => null,
                'ccet_adaptation' => null,
                'ccet_mitigation' => null,
                'cc_typology_id' => null,
            ],
            [
                'id' => 44,
                'aip_entry_id' => 44,
                'funding_source_id' => '5% GAD',
                'ps_amount' => null,
                'mooe_amount' => 50,
                'fe_amount' => null,
                'co_amount' => null,
                'ccet_adaptation' => null,
                'ccet_mitigation' => null,
                'cc_typology_id' => null,
            ],
            [
                'id' => 45,
                'aip_entry_id' => 45,
                'funding_source_id' => '5% GAD',
                'ps_amount' => null,
                'mooe_amount' => 50,
                'fe_amount' => null,
                'co_amount' => null,
                'ccet_adaptation' => null,
                'ccet_mitigation' => null,
                'cc_typology_id' => null,
            ],
            [
                'id' => 46,
                'aip_entry_id' => 46,
                'funding_source_id' => null,
                'ps_amount' => null,
                'mooe_amount' => null,
                'fe_amount' => null,
                'co_amount' => null,
                'ccet_adaptation' => null,
                'ccet_mitigation' => null,
                'cc_typology_id' => null,
            ],
            [
                'id' => 47,
                'aip_entry_id' => 47,
                'funding_source_id' => 'GF-Proper',
                'ps_amount' => null,
                'mooe_amount' => 1500,
                'fe_amount' => null,
                'co_amount' => null,
                'ccet_adaptation' => null,
                'ccet_mitigation' => null,
                'cc_typology_id' => null,
            ],
            [
                'id' => 48,
                'aip_entry_id' => 48,
                'funding_source_id' => null,
                'ps_amount' => null,
                'mooe_amount' => null,
                'fe_amount' => null,
                'co_amount' => null,
                'ccet_adaptation' => null,
                'ccet_mitigation' => null,
                'cc_typology_id' => null,
            ],
            [
                'id' => 49,
                'aip_entry_id' => 49,
                'funding_source_id' => null,
                'ps_amount' => null,
                'mooe_amount' => null,
                'fe_amount' => null,
                'co_amount' => null,
                'ccet_adaptation' => null,
                'ccet_mitigation' => null,
                'cc_typology_id' => null,
            ],
            [
                'id' => 50,
                'aip_entry_id' => 50,
                'funding_source_id' => null,
                'ps_amount' => null,
                'mooe_amount' => null,
                'fe_amount' => null,
                'co_amount' => null,
                'ccet_adaptation' => null,
                'ccet_mitigation' => null,
                'cc_typology_id' => null,
            ],
            [
                'id' => 51,
                'aip_entry_id' => 51,
                'funding_source_id' => 'GF-Proper',
                'ps_amount' => null,
                'mooe_amount' => 90,
                'fe_amount' => null,
                'co_amount' => null,
                'ccet_adaptation' => null,
                'ccet_mitigation' => null,
                'cc_typology_id' => null,
            ],
            [
                'id' => 52,
                'aip_entry_id' => 52,
                'funding_source_id' => null,
                'ps_amount' => null,
                'mooe_amount' => null,
                'fe_amount' => null,
                'co_amount' => null,
                'ccet_adaptation' => null,
                'ccet_mitigation' => null,
                'cc_typology_id' => null,
            ],
            [
                'id' => 53,
                'aip_entry_id' => 53,
                'funding_source_id' => null,
                'ps_amount' => null,
                'mooe_amount' => null,
                'fe_amount' => null,
                'co_amount' => null,
                'ccet_adaptation' => null,
                'ccet_mitigation' => null,
                'cc_typology_id' => null,
            ],
            [
                'id' => 54,
                'aip_entry_id' => 54,
                'funding_source_id' => null,
                'ps_amount' => null,
                'mooe_amount' => null,
                'fe_amount' => null,
                'co_amount' => null,
                'ccet_adaptation' => null,
                'ccet_mitigation' => null,
                'cc_typology_id' => null,
            ],
            [
                'id' => 55,
                'aip_entry_id' => 55,
                'funding_source_id' => null,
                'ps_amount' => null,
                'mooe_amount' => null,
                'fe_amount' => null,
                'co_amount' => null,
                'ccet_adaptation' => null,
                'ccet_mitigation' => null,
                'cc_typology_id' => null,
            ],
            [
                'id' => 56,
                'aip_entry_id' => 56,
                'funding_source_id' => null,
                'ps_amount' => null,
                'mooe_amount' => null,
                'fe_amount' => null,
                'co_amount' => null,
                'ccet_adaptation' => null,
                'ccet_mitigation' => null,
                'cc_typology_id' => null,
            ],
            [
                'id' => 57,
                'aip_entry_id' => 57,
                'funding_source_id' => 'GF-Proper',
                'ps_amount' => null,
                'mooe_amount' => 250,
                'fe_amount' => null,
                'co_amount' => null,
                'ccet_adaptation' => null,
                'ccet_mitigation' => null,
                'cc_typology_id' => null,
            ],
            [
                'id' => 58,
                'aip_entry_id' => 58,
                'funding_source_id' => null,
                'ps_amount' => null,
                'mooe_amount' => null,
                'fe_amount' => null,
                'co_amount' => null,
                'ccet_adaptation' => null,
                'ccet_mitigation' => null,
                'cc_typology_id' => null,
            ],
            [
                'id' => 59,
                'aip_entry_id' => 59,
                'funding_source_id' => null,
                'ps_amount' => null,
                'mooe_amount' => null,
                'fe_amount' => null,
                'co_amount' => null,
                'ccet_adaptation' => null,
                'ccet_mitigation' => null,
                'cc_typology_id' => null,
            ],
            [
                'id' => 60,
                'aip_entry_id' => 60,
                'funding_source_id' => null,
                'ps_amount' => null,
                'mooe_amount' => null,
                'fe_amount' => null,
                'co_amount' => null,
                'ccet_adaptation' => null,
                'ccet_mitigation' => null,
                'cc_typology_id' => null,
            ],
            [
                'id' => 61,
                'aip_entry_id' => 61,
                'funding_source_id' => null,
                'ps_amount' => null,
                'mooe_amount' => null,
                'fe_amount' => null,
                'co_amount' => null,
                'ccet_adaptation' => null,
                'ccet_mitigation' => null,
                'cc_typology_id' => null,
            ],
            [
                'id' => 62,
                'aip_entry_id' => 62,
                'funding_source_id' => null,
                'ps_amount' => null,
                'mooe_amount' => null,
                'fe_amount' => null,
                'co_amount' => null,
                'ccet_adaptation' => null,
                'ccet_mitigation' => null,
                'cc_typology_id' => null,
            ],
            [
                'id' => 63,
                'aip_entry_id' => 63,
                'funding_source_id' => null,
                'ps_amount' => null,
                'mooe_amount' => null,
                'fe_amount' => null,
                'co_amount' => null,
                'ccet_adaptation' => null,
                'ccet_mitigation' => null,
                'cc_typology_id' => null,
            ],
            [
                'id' => 64,
                'aip_entry_id' => 64,
                'funding_source_id' => 'GF-Proper',
                'ps_amount' => null,
                'mooe_amount' => 500,
                'fe_amount' => null,
                'co_amount' => null,
                'ccet_adaptation' => null,
                'ccet_mitigation' => null,
                'cc_typology_id' => null,
            ],
            [
                'id' => 65,
                'aip_entry_id' => 65,
                'funding_source_id' => 'GF-Proper',
                'ps_amount' => null,
                'mooe_amount' => 16500,
                'fe_amount' => null,
                'co_amount' => 150,
                'ccet_adaptation' => null,
                'ccet_mitigation' => null,
                'cc_typology_id' => null,
            ],
            [
                'id' => 66,
                'aip_entry_id' => 66,
                'funding_source_id' => 'GF-Proper',
                'ps_amount' => null,
                'mooe_amount' => 500,
                'fe_amount' => null,
                'co_amount' => null,
                'ccet_adaptation' => null,
                'ccet_mitigation' => null,
                'cc_typology_id' => null,
            ],
            [
                'id' => 67,
                'aip_entry_id' => 67,
                'funding_source_id' => 'GF-Proper',
                'ps_amount' => null,
                'mooe_amount' => 400,
                'fe_amount' => null,
                'co_amount' => null,
                'ccet_adaptation' => null,
                'ccet_mitigation' => null,
                'cc_typology_id' => null,
            ],
            [
                'id' => 68,
                'aip_entry_id' => 68,
                'funding_source_id' => null,
                'ps_amount' => null,
                'mooe_amount' => null,
                'fe_amount' => null,
                'co_amount' => null,
                'ccet_adaptation' => null,
                'ccet_mitigation' => null,
                'cc_typology_id' => null,
            ],
            [
                'id' => 69,
                'aip_entry_id' => 69,
                'funding_source_id' => null,
                'ps_amount' => null,
                'mooe_amount' => null,
                'fe_amount' => null,
                'co_amount' => null,
                'ccet_adaptation' => null,
                'ccet_mitigation' => null,
                'cc_typology_id' => null,
            ],
            [
                'id' => 70,
                'aip_entry_id' => 70,
                'funding_source_id' => 'GF-Proper',
                'ps_amount' => null,
                'mooe_amount' => 1000,
                'fe_amount' => null,
                'co_amount' => null,
                'ccet_adaptation' => null,
                'ccet_mitigation' => null,
                'cc_typology_id' => null,
            ],
            [
                'id' => 71,
                'aip_entry_id' => 71,
                'funding_source_id' => 'GF-Proper',
                'ps_amount' => null,
                'mooe_amount' => 500,
                'fe_amount' => null,
                'co_amount' => null,
                'ccet_adaptation' => null,
                'ccet_mitigation' => null,
                'cc_typology_id' => null,
            ],
            [
                'id' => 72,
                'aip_entry_id' => 72,
                'funding_source_id' => 'GF-Proper',
                'ps_amount' => null,
                'mooe_amount' => 500,
                'fe_amount' => null,
                'co_amount' => null,
                'ccet_adaptation' => null,
                'ccet_mitigation' => null,
                'cc_typology_id' => null,
            ],
            [
                'id' => 73,
                'aip_entry_id' => 73,
                'funding_source_id' => null,
                'ps_amount' => null,
                'mooe_amount' => null,
                'fe_amount' => null,
                'co_amount' => null,
                'ccet_adaptation' => null,
                'ccet_mitigation' => null,
                'cc_typology_id' => null,
            ],
            [
                'id' => 74,
                'aip_entry_id' => 74,
                'funding_source_id' => null,
                'ps_amount' => null,
                'mooe_amount' => null,
                'fe_amount' => null,
                'co_amount' => null,
                'ccet_adaptation' => null,
                'ccet_mitigation' => null,
                'cc_typology_id' => null,
            ],
            [
                'id' => 75,
                'aip_entry_id' => 75,
                'funding_source_id' => 'GF-Proper',
                'ps_amount' => null,
                'mooe_amount' => 2000,
                'fe_amount' => null,
                'co_amount' => null,
                'ccet_adaptation' => null,
                'ccet_mitigation' => null,
                'cc_typology_id' => null,
            ],
            [
                'id' => 76,
                'aip_entry_id' => 76,
                'funding_source_id' => null,
                'ps_amount' => null,
                'mooe_amount' => null,
                'fe_amount' => null,
                'co_amount' => null,
                'ccet_adaptation' => null,
                'ccet_mitigation' => null,
                'cc_typology_id' => null,
            ],
            [
                'id' => 77,
                'aip_entry_id' => 77,
                'funding_source_id' => null,
                'ps_amount' => null,
                'mooe_amount' => null,
                'fe_amount' => null,
                'co_amount' => null,
                'ccet_adaptation' => null,
                'ccet_mitigation' => null,
                'cc_typology_id' => null,
            ],
            [
                'id' => 78,
                'aip_entry_id' => 78,
                'funding_source_id' => null,
                'ps_amount' => null,
                'mooe_amount' => null,
                'fe_amount' => null,
                'co_amount' => null,
                'ccet_adaptation' => null,
                'ccet_mitigation' => null,
                'cc_typology_id' => null,
            ],
            [
                'id' => 79,
                'aip_entry_id' => 79,
                'funding_source_id' => null,
                'ps_amount' => null,
                'mooe_amount' => null,
                'fe_amount' => null,
                'co_amount' => null,
                'ccet_adaptation' => null,
                'ccet_mitigation' => null,
                'cc_typology_id' => null,
            ],
            [
                'id' => 80,
                'aip_entry_id' => 80,
                'funding_source_id' => null,
                'ps_amount' => null,
                'mooe_amount' => null,
                'fe_amount' => null,
                'co_amount' => null,
                'ccet_adaptation' => null,
                'ccet_mitigation' => null,
                'cc_typology_id' => null,
            ],
            [
                'id' => 81,
                'aip_entry_id' => 81,
                'funding_source_id' => 'GF-Proper',
                'ps_amount' => null,
                'mooe_amount' => 1000,
                'fe_amount' => null,
                'co_amount' => null,
                'ccet_adaptation' => null,
                'ccet_mitigation' => null,
                'cc_typology_id' => null,
            ],
            [
                'id' => 82,
                'aip_entry_id' => 82,
                'funding_source_id' => null,
                'ps_amount' => null,
                'mooe_amount' => null,
                'fe_amount' => null,
                'co_amount' => null,
                'ccet_adaptation' => null,
                'ccet_mitigation' => null,
                'cc_typology_id' => null,
            ],
            [
                'id' => 83,
                'aip_entry_id' => 83,
                'funding_source_id' => null,
                'ps_amount' => null,
                'mooe_amount' => null,
                'fe_amount' => null,
                'co_amount' => null,
                'ccet_adaptation' => null,
                'ccet_mitigation' => null,
                'cc_typology_id' => null,
            ],
            [
                'id' => 84,
                'aip_entry_id' => 84,
                'funding_source_id' => null,
                'ps_amount' => null,
                'mooe_amount' => null,
                'fe_amount' => null,
                'co_amount' => null,
                'ccet_adaptation' => null,
                'ccet_mitigation' => null,
                'cc_typology_id' => null,
            ],
            [
                'id' => 85,
                'aip_entry_id' => 85,
                'funding_source_id' => null,
                'ps_amount' => null,
                'mooe_amount' => null,
                'fe_amount' => null,
                'co_amount' => null,
                'ccet_adaptation' => null,
                'ccet_mitigation' => null,
                'cc_typology_id' => null,
            ],
            [
                'id' => 86,
                'aip_entry_id' => 86,
                'funding_source_id' => null,
                'ps_amount' => null,
                'mooe_amount' => null,
                'fe_amount' => null,
                'co_amount' => null,
                'ccet_adaptation' => null,
                'ccet_mitigation' => null,
                'cc_typology_id' => null,
            ],
            [
                'id' => 87,
                'aip_entry_id' => 87,
                'funding_source_id' => null,
                'ps_amount' => null,
                'mooe_amount' => null,
                'fe_amount' => null,
                'co_amount' => null,
                'ccet_adaptation' => null,
                'ccet_mitigation' => null,
                'cc_typology_id' => null,
            ],
            [
                'id' => 88,
                'aip_entry_id' => 88,
                'funding_source_id' => null,
                'ps_amount' => null,
                'mooe_amount' => null,
                'fe_amount' => null,
                'co_amount' => null,
                'ccet_adaptation' => null,
                'ccet_mitigation' => null,
                'cc_typology_id' => null,
            ],
            [
                'id' => 89,
                'aip_entry_id' => 89,
                'funding_source_id' => null,
                'ps_amount' => null,
                'mooe_amount' => null,
                'fe_amount' => null,
                'co_amount' => null,
                'ccet_adaptation' => null,
                'ccet_mitigation' => null,
                'cc_typology_id' => null,
            ],
            [
                'id' => 90,
                'aip_entry_id' => 90,
                'funding_source_id' => null,
                'ps_amount' => null,
                'mooe_amount' => null,
                'fe_amount' => null,
                'co_amount' => null,
                'ccet_adaptation' => null,
                'ccet_mitigation' => null,
                'cc_typology_id' => null,
            ],
            [
                'id' => 91,
                'aip_entry_id' => 91,
                'funding_source_id' => null,
                'ps_amount' => null,
                'mooe_amount' => null,
                'fe_amount' => null,
                'co_amount' => null,
                'ccet_adaptation' => null,
                'ccet_mitigation' => null,
                'cc_typology_id' => null,
            ],
            [
                'id' => 92,
                'aip_entry_id' => 92,
                'funding_source_id' => null,
                'ps_amount' => null,
                'mooe_amount' => null,
                'fe_amount' => null,
                'co_amount' => null,
                'ccet_adaptation' => null,
                'ccet_mitigation' => null,
                'cc_typology_id' => null,
            ],
            [
                'id' => 93,
                'aip_entry_id' => 93,
                'funding_source_id' => 'GF-Proper',
                'ps_amount' => null,
                'mooe_amount' => 250,
                'fe_amount' => null,
                'co_amount' => null,
                'ccet_adaptation' => null,
                'ccet_mitigation' => null,
                'cc_typology_id' => null,
            ],
            [
                'id' => 94,
                'aip_entry_id' => 94,
                'funding_source_id' => 'GF-Proper',
                'ps_amount' => null,
                'mooe_amount' => 100,
                'fe_amount' => null,
                'co_amount' => null,
                'ccet_adaptation' => null,
                'ccet_mitigation' => null,
                'cc_typology_id' => null,
            ],
            [
                'id' => 95,
                'aip_entry_id' => 95,
                'funding_source_id' => null,
                'ps_amount' => null,
                'mooe_amount' => null,
                'fe_amount' => null,
                'co_amount' => null,
                'ccet_adaptation' => null,
                'ccet_mitigation' => null,
                'cc_typology_id' => null,
            ],
            [
                'id' => 96,
                'aip_entry_id' => 96,
                'funding_source_id' => null,
                'ps_amount' => null,
                'mooe_amount' => null,
                'fe_amount' => null,
                'co_amount' => null,
                'ccet_adaptation' => null,
                'ccet_mitigation' => null,
                'cc_typology_id' => null,
            ],
            [
                'id' => 97,
                'aip_entry_id' => 97,
                'funding_source_id' => null,
                'ps_amount' => null,
                'mooe_amount' => null,
                'fe_amount' => null,
                'co_amount' => null,
                'ccet_adaptation' => null,
                'ccet_mitigation' => null,
                'cc_typology_id' => null,
            ],
            [
                'id' => 98,
                'aip_entry_id' => 98,
                'funding_source_id' => null,
                'ps_amount' => null,
                'mooe_amount' => null,
                'fe_amount' => null,
                'co_amount' => null,
                'ccet_adaptation' => null,
                'ccet_mitigation' => null,
                'cc_typology_id' => null,
            ],
            [
                'id' => 99,
                'aip_entry_id' => 99,
                'funding_source_id' => null,
                'ps_amount' => null,
                'mooe_amount' => null,
                'fe_amount' => null,
                'co_amount' => null,
                'ccet_adaptation' => null,
                'ccet_mitigation' => null,
                'cc_typology_id' => null,
            ],
            [
                'id' => 100,
                'aip_entry_id' => 100,
                'funding_source_id' => 'GF-Proper',
                'ps_amount' => null,
                'mooe_amount' => 50,
                'fe_amount' => null,
                'co_amount' => null,
                'ccet_adaptation' => null,
                'ccet_mitigation' => null,
                'cc_typology_id' => null,
            ],
            [
                'id' => 101,
                'aip_entry_id' => 101,
                'funding_source_id' => 'GF-Proper',
                'ps_amount' => null,
                'mooe_amount' => 20,
                'fe_amount' => null,
                'co_amount' => null,
                'ccet_adaptation' => null,
                'ccet_mitigation' => null,
                'cc_typology_id' => null,
            ],
            [
                'id' => 102,
                'aip_entry_id' => 102,
                'funding_source_id' => null,
                'ps_amount' => null,
                'mooe_amount' => null,
                'fe_amount' => null,
                'co_amount' => null,
                'ccet_adaptation' => null,
                'ccet_mitigation' => null,
                'cc_typology_id' => null,
            ],
            [
                'id' => 103,
                'aip_entry_id' => 103,
                'funding_source_id' => null,
                'ps_amount' => null,
                'mooe_amount' => null,
                'fe_amount' => null,
                'co_amount' => null,
                'ccet_adaptation' => null,
                'ccet_mitigation' => null,
                'cc_typology_id' => null,
            ],
            [
                'id' => 104,
                'aip_entry_id' => 104,
                'funding_source_id' => null,
                'ps_amount' => null,
                'mooe_amount' => null,
                'fe_amount' => null,
                'co_amount' => null,
                'ccet_adaptation' => null,
                'ccet_mitigation' => null,
                'cc_typology_id' => null,
            ],
            [
                'id' => 105,
                'aip_entry_id' => 105,
                'funding_source_id' => 'GF-Proper',
                'ps_amount' => null,
                'mooe_amount' => 30,
                'fe_amount' => null,
                'co_amount' => null,
                'ccet_adaptation' => null,
                'ccet_mitigation' => null,
                'cc_typology_id' => null,
            ],
            [
                'id' => 106,
                'aip_entry_id' => 106,
                'funding_source_id' => 'GF-Proper',
                'ps_amount' => null,
                'mooe_amount' => 100,
                'fe_amount' => null,
                'co_amount' => null,
                'ccet_adaptation' => null,
                'ccet_mitigation' => null,
                'cc_typology_id' => null,
            ],
            [
                'id' => 107,
                'aip_entry_id' => 107,
                'funding_source_id' => null,
                'ps_amount' => null,
                'mooe_amount' => null,
                'fe_amount' => null,
                'co_amount' => null,
                'ccet_adaptation' => null,
                'ccet_mitigation' => null,
                'cc_typology_id' => null,
            ],
            [
                'id' => 108,
                'aip_entry_id' => 108,
                'funding_source_id' => null,
                'ps_amount' => null,
                'mooe_amount' => null,
                'fe_amount' => null,
                'co_amount' => null,
                'ccet_adaptation' => null,
                'ccet_mitigation' => null,
                'cc_typology_id' => null,
            ],
            [
                'id' => 109,
                'aip_entry_id' => 109,
                'funding_source_id' => null,
                'ps_amount' => null,
                'mooe_amount' => null,
                'fe_amount' => null,
                'co_amount' => null,
                'ccet_adaptation' => null,
                'ccet_mitigation' => null,
                'cc_typology_id' => null,
            ],
            [
                'id' => 110,
                'aip_entry_id' => 110,
                'funding_source_id' => null,
                'ps_amount' => null,
                'mooe_amount' => null,
                'fe_amount' => null,
                'co_amount' => null,
                'ccet_adaptation' => null,
                'ccet_mitigation' => null,
                'cc_typology_id' => null,
            ],
            [
                'id' => 111,
                'aip_entry_id' => 111,
                'funding_source_id' => null,
                'ps_amount' => null,
                'mooe_amount' => null,
                'fe_amount' => null,
                'co_amount' => null,
                'ccet_adaptation' => null,
                'ccet_mitigation' => null,
                'cc_typology_id' => null,
            ],
            [
                'id' => 112,
                'aip_entry_id' => 112,
                'funding_source_id' => null,
                'ps_amount' => null,
                'mooe_amount' => null,
                'fe_amount' => null,
                'co_amount' => null,
                'ccet_adaptation' => null,
                'ccet_mitigation' => null,
                'cc_typology_id' => null,
            ],
            [
                'id' => 113,
                'aip_entry_id' => 113,
                'funding_source_id' => null,
                'ps_amount' => null,
                'mooe_amount' => null,
                'fe_amount' => null,
                'co_amount' => null,
                'ccet_adaptation' => null,
                'ccet_mitigation' => null,
                'cc_typology_id' => null,
            ],
            [
                'id' => 114,
                'aip_entry_id' => 114,
                'funding_source_id' => null,
                'ps_amount' => null,
                'mooe_amount' => null,
                'fe_amount' => null,
                'co_amount' => null,
                'ccet_adaptation' => null,
                'ccet_mitigation' => null,
                'cc_typology_id' => null,
            ],
            [
                'id' => 115,
                'aip_entry_id' => 115,
                'funding_source_id' => null,
                'ps_amount' => null,
                'mooe_amount' => null,
                'fe_amount' => null,
                'co_amount' => null,
                'ccet_adaptation' => null,
                'ccet_mitigation' => null,
                'cc_typology_id' => null,
            ],
            [
                'id' => 116,
                'aip_entry_id' => 116,
                'funding_source_id' => null,
                'ps_amount' => null,
                'mooe_amount' => null,
                'fe_amount' => null,
                'co_amount' => null,
                'ccet_adaptation' => null,
                'ccet_mitigation' => null,
                'cc_typology_id' => null,
            ],
            [
                'id' => 117,
                'aip_entry_id' => 117,
                'funding_source_id' => null,
                'ps_amount' => null,
                'mooe_amount' => null,
                'fe_amount' => null,
                'co_amount' => null,
                'ccet_adaptation' => null,
                'ccet_mitigation' => null,
                'cc_typology_id' => null,
            ],
            [
                'id' => 118,
                'aip_entry_id' => 118,
                'funding_source_id' => 'GF-Proper',
                'ps_amount' => null,
                'mooe_amount' => 20,
                'fe_amount' => null,
                'co_amount' => null,
                'ccet_adaptation' => null,
                'ccet_mitigation' => null,
                'cc_typology_id' => null,
            ],
            [
                'id' => 119,
                'aip_entry_id' => 119,
                'funding_source_id' => null,
                'ps_amount' => null,
                'mooe_amount' => null,
                'fe_amount' => null,
                'co_amount' => null,
                'ccet_adaptation' => null,
                'ccet_mitigation' => null,
                'cc_typology_id' => null,
            ],
            [
                'id' => 120,
                'aip_entry_id' => 120,
                'funding_source_id' => null,
                'ps_amount' => null,
                'mooe_amount' => null,
                'fe_amount' => null,
                'co_amount' => null,
                'ccet_adaptation' => null,
                'ccet_mitigation' => null,
                'cc_typology_id' => null,
            ],
            [
                'id' => 121,
                'aip_entry_id' => 121,
                'funding_source_id' => null,
                'ps_amount' => null,
                'mooe_amount' => null,
                'fe_amount' => null,
                'co_amount' => null,
                'ccet_adaptation' => null,
                'ccet_mitigation' => null,
                'cc_typology_id' => null,
            ],
            [
                'id' => 122,
                'aip_entry_id' => 122,
                'funding_source_id' => 'GF-Proper',
                'ps_amount' => null,
                'mooe_amount' => 20,
                'fe_amount' => null,
                'co_amount' => null,
                'ccet_adaptation' => null,
                'ccet_mitigation' => null,
                'cc_typology_id' => null,
            ],
            [
                'id' => 123,
                'aip_entry_id' => 123,
                'funding_source_id' => 'GF-Proper',
                'ps_amount' => null,
                'mooe_amount' => 250,
                'fe_amount' => null,
                'co_amount' => null,
                'ccet_adaptation' => null,
                'ccet_mitigation' => null,
                'cc_typology_id' => null,
            ],
            [
                'id' => 124,
                'aip_entry_id' => 124,
                'funding_source_id' => 'GF-Proper',
                'ps_amount' => null,
                'mooe_amount' => 200,
                'fe_amount' => null,
                'co_amount' => null,
                'ccet_adaptation' => null,
                'ccet_mitigation' => null,
                'cc_typology_id' => null,
            ],
            [
                'id' => 125,
                'aip_entry_id' => 125,
                'funding_source_id' => 'GF-Proper',
                'ps_amount' => null,
                'mooe_amount' => 100,
                'fe_amount' => null,
                'co_amount' => null,
                'ccet_adaptation' => null,
                'ccet_mitigation' => null,
                'cc_typology_id' => null,
            ],
            [
                'id' => 126,
                'aip_entry_id' => 126,
                'funding_source_id' => 'GF-Proper',
                'ps_amount' => null,
                'mooe_amount' => 30,
                'fe_amount' => null,
                'co_amount' => null,
                'ccet_adaptation' => null,
                'ccet_mitigation' => null,
                'cc_typology_id' => null,
            ],
            [
                'id' => 127,
                'aip_entry_id' => 127,
                'funding_source_id' => 'GF-Proper',
                'ps_amount' => null,
                'mooe_amount' => 1000,
                'fe_amount' => null,
                'co_amount' => 5000,
                'ccet_adaptation' => null,
                'ccet_mitigation' => null,
                'cc_typology_id' => null,
            ],
            [
                'id' => 128,
                'aip_entry_id' => 128,
                'funding_source_id' => null,
                'ps_amount' => null,
                'mooe_amount' => null,
                'fe_amount' => null,
                'co_amount' => null,
                'ccet_adaptation' => null,
                'ccet_mitigation' => null,
                'cc_typology_id' => null,
            ],
            [
                'id' => 129,
                'aip_entry_id' => 129,
                'funding_source_id' => 'GF-Proper',
                'ps_amount' => null,
                'mooe_amount' => null,
                'fe_amount' => 30000,
                'co_amount' => null,
                'ccet_adaptation' => null,
                'ccet_mitigation' => null,
                'cc_typology_id' => null,
            ],
            [
                'id' => 130,
                'aip_entry_id' => 130,
                'funding_source_id' => 'GF-Proper',
                'ps_amount' => null,
                'mooe_amount' => null,
                'fe_amount' => 40000,
                'co_amount' => null,
                'ccet_adaptation' => null,
                'ccet_mitigation' => null,
                'cc_typology_id' => null,
            ],
        ];

        // Validate all seeder codes have a map entry
        $usedCodes = collect($ppaFundingSources)
            ->pluck('funding_source_id')
            ->filter()
            ->unique()
            ->values();

        $unmapped = $usedCodes->reject(fn($code) => isset($codeMap[$code]));

        if ($unmapped->isNotEmpty()) {
            $this->command->error(
                'Missing code map entries for: ' . $unmapped->implode(', '),
            );

            return;
        }

        // Validate all mapped codes exist in the database
        $missingCodes = collect($codeMap)
            ->reject(fn($dbCode) => isset($fundingSources[$dbCode]))
            ->values();

        if ($missingCodes->isNotEmpty()) {
            $this->command->error(
                'Funding source codes not found in database: ' .
                    $missingCodes->implode(', '),
            );

            return;
        }

        foreach ($ppaFundingSources as $ppaFundingSource) {
            PpaFundingSource::create([
                'id' => $ppaFundingSource['id'],
                'aip_entry_id' => $ppaFundingSource['aip_entry_id'],
                'funding_source_id' => $ppaFundingSource['funding_source_id']
                    ? $fundingSources[
                            $codeMap[$ppaFundingSource['funding_source_id']]
                        ] ?? null
                    : null,
                'ps_amount' => $ppaFundingSource['ps_amount'] ?? 0,
                'mooe_amount' => $ppaFundingSource['mooe_amount'] ?? 0,
                'fe_amount' => $ppaFundingSource['fe_amount'] ?? 0,
                'co_amount' => $ppaFundingSource['co_amount'] ?? 0,
                'ccet_adaptation' => $ppaFundingSource['ccet_adaptation'] ?? 0,
                'ccet_mitigation' => $ppaFundingSource['ccet_mitigation'] ?? 0,
                'cc_typology_id' => $ppaFundingSource['cc_typology_id'],
            ]);
        }
    }
}
