export default [
    {
        occupational_service_code: '01-GA',
        name: 'GENERAL ADMINISTRATIVE SERVICE',
        groups: [
            { group_code: 'ADS', group_name: 'Administrative' },
            {
                group_code: 'CSET',
                group_name: 'Clerical/Secretarial/Stenographic',
            },
            { group_code: 'HRM', group_name: 'Human Resource Management' },
            { group_code: 'RM', group_name: 'Records Management' },
            { group_code: 'SUM', group_name: 'Supply Management' },
        ],
    },
    {
        occupational_service_code: '02-FS',
        name: 'FINANCIAL SERVICE',
        groups: [
            { group_code: 'AC', group_name: 'Accounting' },
            { group_code: 'AL', group_name: 'Accounts Liquidation' },
            { group_code: 'AM', group_name: 'Assessment' },
            {
                group_code: 'AFE',
                group_name: 'Auditing and Fiscal Examination',
            },
            {
                group_code: 'BFCB',
                group_name: 'Bonds and Financial Claims Processing',
            },
            { group_code: 'B', group_name: 'Budgeting' },
            { group_code: 'CH', group_name: 'Cashiering' },
            { group_code: 'CC', group_name: 'Credit Collection' },
            { group_code: 'CO', group_name: 'Customs Operations' },
            { group_code: 'FO', group_name: 'Finance Operations' },
            { group_code: 'LI', group_name: 'License Inspection' },
            { group_code: 'LEXA', group_name: 'Loan Examination' },
            { group_code: 'LTO', group_name: 'Local Treasury Operations' },
            { group_code: 'MS', group_name: 'Management Service' },
            { group_code: 'PRA', group_name: 'Property Appraisal' },
            { group_code: 'PM', group_name: 'Procurement Management' },
            {
                group_code: 'RCEP',
                group_name: 'Revenue Collection, Examination and Planning',
            },
            { group_code: 'TREO', group_name: 'Treasury Operations' },
        ],
    },
    {
        occupational_service_code: '03-PS',
        name: 'PLANNING SERVICE',
        groups: [
            { group_code: 'DM', group_name: 'Development Management' },
            { group_code: 'ED', group_name: 'Economic Development' },
            { group_code: 'EC', group_name: 'Economics' },
            { group_code: 'IT', group_name: 'Information Technology' },
            { group_code: 'PL', group_name: 'Planning' },
            {
                group_code: 'PPC',
                group_name: 'Production Planning and Control',
            },
            {
                group_code: 'PDE',
                group_name: 'Project Development and Evaluation',
            },
            { group_code: 'STC', group_name: 'Statistical Coordination' },
            { group_code: 'ST', group_name: 'Statistics' },
        ],
    },
    {
        occupational_service_code: '04-AE',
        name: 'ARCHITECTURE AND ENGINEERING SERVICE',
        groups: [
            {
                group_code: 'AMT',
                group_name: 'Aircraft Maintenance Technology',
            },
            { group_code: 'AT', group_name: 'Airways Technology' },
            { group_code: 'AR', group_name: 'Architecture' },
            { group_code: 'BR', group_name: 'Building Regulation' },
            { group_code: 'CR', group_name: 'Cartography' },
            { group_code: 'DF', group_name: 'Drafting' },
            { group_code: 'DO', group_name: 'Dredge Operation' },
            { group_code: 'EN', group_name: 'Engineering' },
            { group_code: 'SZ', group_name: 'Surveying and Zoning' },
            { group_code: 'TM', group_name: 'Tax Mapping' },
            {
                group_code: 'WRSD',
                group_name: 'Water Resource and Systems Development',
            },
        ],
    },
    {
        occupational_service_code: '05-TC',
        name: 'TRANSPORTATION, COMMUNICATION AND PUBLIC UTILITIES SERVICE',
        groups: [
            { group_code: 'AEO', group_name: 'Automotive Equipment Operation' },
            { group_code: 'AV', group_name: 'Aviation' },
            {
                group_code: 'CDOR',
                group_name: 'Communications Development, Operation and Repair',
            },
            {
                group_code: 'FSCH',
                group_name: 'Freight Service and Cargo Handling',
            },
            { group_code: 'LO', group_name: 'Lighthouse Operation' },
            { group_code: 'MTS', group_name: 'Maritime Service' },
            {
                group_code: 'PUAR',
                group_name: 'Public Utilities Administration and Regulation',
            },
            {
                group_code: 'TDR',
                group_name: 'Transportation Development and Regulation',
            },
        ],
    },
    {
        occupational_service_code: '06-CT',
        name: 'CRAFTS, TRADES AND RELATED SERVICE',
        groups: [
            { group_code: 'BW', group_name: 'Bench Working' },
            {
                group_code: 'BGHC',
                group_name:
                    'Buildings, Grounds and Highways Construction and Maintenance',
            },
            { group_code: 'GUS', group_name: 'General Utility Services' },
            { group_code: 'LS', group_name: 'Laboratory Services' },
            { group_code: 'MHOR', group_name: 'Machine Operation and Repair' },
            { group_code: 'MW', group_name: 'Metal Working' },
            { group_code: 'PW', group_name: 'Paper Working' },
            { group_code: 'PMO', group_name: 'Printing Machine Operation' },
        ],
    },
    {
        occupational_service_code: '07-SS',
        name: 'SOCIAL SCIENCES AND WELFARE SERVICE',
        groups: [
            {
                group_code: 'CAD',
                group_name: 'Community Affairs and Development',
            },
            { group_code: 'DRM', group_name: 'Disaster Risk Management' },
            { group_code: 'EAD', group_name: 'Election Administration' },
            { group_code: 'ES', group_name: 'Emigrant Services' },
            {
                group_code: 'GAD',
                group_name: 'Gender and Awareness Development',
            },
            { group_code: 'GPC', group_name: 'Graft Prevention and Control' },
            { group_code: 'HM', group_name: 'Home Management' },
            {
                group_code: 'HHR',
                group_name: 'Housing and Homesite Regulation',
            },
            { group_code: 'IMR', group_name: 'Immigration Regulation' },
            {
                group_code: 'LCMA',
                group_name: 'Labor, Conciliation, Mediation and Arbitration',
            },
            {
                group_code: 'LEMD',
                group_name: 'Labor, Employment and Manpower Development',
            },
            { group_code: 'LGO', group_name: 'Local Government Operations' },
            {
                group_code: 'PPA',
                group_name: 'Parole and Probation Administration',
            },
            { group_code: 'PP', group_name: 'Peace Program' },
            { group_code: 'PIM', group_name: 'Penal Institution Management' },
            { group_code: 'PAF', group_name: 'Political Affairs' },
            { group_code: 'PCL', group_name: 'Population Control Program' },
            { group_code: 'PR', group_name: 'Professional Regulation' },
            { group_code: 'PS', group_name: 'Public Services' },
            { group_code: 'R', group_name: 'Registration' },
            { group_code: 'RG', group_name: 'Religious Guidance' },
            { group_code: 'SWD', group_name: 'Social Welfare Development' },
            { group_code: 'S', group_name: 'Sociology' },
            { group_code: 'SO', group_name: 'Special Operations' },
            {
                group_code: 'TESD',
                group_name: 'Technical Education and Skills Development',
            },
            { group_code: 'VA', group_name: 'Veterans Assistance' },
        ],
    },
    {
        occupational_service_code: '08-IA',
        name: 'INFORMATION, ART AND RECREATION SERVICE',
        groups: [
            {
                group_code: 'AVEO',
                group_name: 'Audio-Visual Equipment Operation and Repair',
            },
            {
                group_code: 'BOPP',
                group_name: 'Broadcast Operation and Program Production',
            },
            { group_code: 'FC', group_name: 'Film Classification' },
            { group_code: 'I', group_name: 'Illustrating' },
            { group_code: 'ID', group_name: 'Information Dissemination' },
            {
                group_code: 'MAR',
                group_name: 'Media Accreditation and Relations',
            },
            { group_code: 'MMP', group_name: 'Media and Movie Production' },
            { group_code: 'MC', group_name: 'Musicians' },
            { group_code: 'PH', group_name: 'Photography' },
            { group_code: 'PAD', group_name: 'Printing Administration' },
            { group_code: 'PF', group_name: 'Proofreading' },
            { group_code: 'PUR', group_name: 'Public Information' },
            { group_code: 'RC', group_name: 'Recreation' },
            {
                group_code: 'SDGR',
                group_name: 'Sports Development and Games Regulation',
            },
            { group_code: 'T', group_name: 'Translating' },
        ],
    },
    {
        occupational_service_code: '09-MH',
        name: 'MEDICINE AND HEALTH SERVICE',
        groups: [
            { group_code: 'D', group_name: 'Dentistry' },
            { group_code: 'DT', group_name: 'Dietetics' },
            { group_code: 'HS', group_name: 'Health and Sanitation' },
            { group_code: 'HEP', group_name: 'Health Education and Promotion' },
            { group_code: 'HPD', group_name: 'Health Program Development' },
            { group_code: 'HA', group_name: 'Hospital Administration' },
            { group_code: 'MT', group_name: 'Medical Technology' },
            { group_code: 'M', group_name: 'Medical' },
            { group_code: 'N', group_name: 'Nursing' },
            {
                group_code: 'OPST',
                group_name: 'Occupational, Physical and Speech Therapy',
            },
            { group_code: 'O', group_name: 'Optometry' },
            { group_code: 'PC', group_name: 'Pest Control' },
            { group_code: 'PY', group_name: 'Pharmacy' },
            { group_code: 'V', group_name: 'Veterinary' },
        ],
    },
    {
        occupational_service_code: '10-EL',
        name: 'EDUCATION, LIBRARY, MUSEUM AND ARCHIVAL SERVICE',
        groups: [
            { group_code: 'ARV', group_name: 'Archival' },
            { group_code: 'CRA', group_name: 'Culture and Arts' },
            {
                group_code: 'ERPS',
                group_name: 'Educational Research, Planning and Supervision',
            },
            { group_code: 'GS', group_name: 'Guidance Services' },
            { group_code: 'HSD', group_name: 'Historic Sites Development' },
            { group_code: 'HR', group_name: 'History Research' },
            { group_code: 'LRES', group_name: 'Language Researcher' },
            { group_code: 'LIN', group_name: 'Linguistics' },
            { group_code: 'LIS', group_name: 'Library Services' },
            { group_code: 'MSC', group_name: 'Museum and Shrine Curation' },
            {
                group_code: 'STCA',
                group_name:
                    'School, College, University and Training Center Administration',
            },
            {
                group_code: 'SCUT',
                group_name: 'School, College and University Teaching',
            },
            { group_code: 'SES', group_name: 'Science Education Services' },
            { group_code: 'SPT', group_name: 'Specialized Training' },
            { group_code: 'TE', group_name: 'Technician Education' },
            { group_code: 'UES', group_name: 'University Extension Services' },
            { group_code: 'URS', group_name: 'University Research Services' },
        ],
    },
    {
        occupational_service_code: '11-AA',
        name: 'AGRARIAN, AGRICULTURAL AND ENVIRONMENT RESOURCES SERVICE',
        groups: [
            { group_code: 'AGR', group_name: 'Agrarian' },
            { group_code: 'AGD', group_name: 'Agricultural Development' },
            { group_code: 'AQD', group_name: 'Aquacultural Development' },
            {
                group_code: 'EERM',
                group_name: 'Ecosystems and Environment Management',
            },
            { group_code: 'ER', group_name: 'Energy Regulation' },
            { group_code: 'FD', group_name: 'Fiber Development' },
            { group_code: 'FA', group_name: 'Forestry Administration' },
            { group_code: 'LM', group_name: 'Land Management' },
            { group_code: 'LREG', group_name: 'Land Registration' },
            { group_code: 'MCE', group_name: 'Mining Claims Examination' },
            { group_code: 'RST', group_name: 'Remote Sensing Technology' },
        ],
    },
    {
        occupational_service_code: '12-TT',
        name: 'TRADE, TOURISM AND INDUSTRY SERVICE',
        groups: [
            { group_code: 'CD', group_name: 'Cooperatives Development' },
            { group_code: 'FPM', group_name: 'Fish Port Management' },
            { group_code: 'IA', group_name: 'Investment Analysis' },
            { group_code: 'IR', group_name: 'Insurance Regulation' },
            { group_code: 'MOR', group_name: 'Market Operations and Research' },
            {
                group_code: 'PTCE',
                group_name: 'Patent, Trademark and Copyright Examination',
            },
            { group_code: 'SPR', group_name: 'Sales Promotion' },
            {
                group_code: 'SER',
                group_name: 'Securities and Exchange Regulation',
            },
            { group_code: 'TO', group_name: 'Tourism Operations' },
            { group_code: 'TRID', group_name: 'Trade-Industry Development' },
        ],
    },
    {
        occupational_service_code: '13-MP',
        name: 'MATHEMATICS, PHYSICAL AND BIOLOGICAL SCIENCES SERVICE',
        groups: [
            { group_code: 'BT', group_name: 'Bacteriology' },
            { group_code: 'BL', group_name: 'Biology' },
            { group_code: 'C', group_name: 'Chemistry' },
            { group_code: 'G', group_name: 'Geology' },
            { group_code: 'GP', group_name: 'Geophysics' },
            { group_code: 'MM', group_name: 'Mathematics' },
            { group_code: 'ML', group_name: 'Metallurgy' },
            { group_code: 'OC', group_name: 'Oceanography' },
            { group_code: 'P', group_name: 'Physics' },
            { group_code: 'SD', group_name: 'Science Development' },
            { group_code: 'WO', group_name: 'Weather Observation' },
            { group_code: 'Z', group_name: 'Zoology' },
        ],
    },
    {
        occupational_service_code: '14-DS',
        name: 'DEFENSE AND SECURITY SERVICE',
        groups: [
            { group_code: 'CDA', group_name: 'Civil Defense Administration' },
            { group_code: 'CSS', group_name: 'Civil Security Services' },
            { group_code: 'CI', group_name: 'Crime Investigation' },
            { group_code: 'DR', group_name: 'Defense Research' },
            {
                group_code: 'FDE',
                group_name: 'Fingerprint and Document Examination',
            },
            { group_code: 'F', group_name: 'Firefighting' },
            { group_code: 'IN', group_name: 'Intelligence' },
            { group_code: 'NI', group_name: 'National Intelligence' },
            { group_code: 'NS', group_name: 'National Security' },
            {
                group_code: 'OMRR',
                group_name: 'Ordnance Manufacture, Regulation and Repair',
            },
            { group_code: 'PA', group_name: 'Police Administration' },
            { group_code: 'SI', group_name: 'Special Investigation' },
            { group_code: 'SPS', group_name: 'Special Police Service' },
            { group_code: 'TRO', group_name: 'Traffic Operations' },
        ],
    },
    {
        occupational_service_code: '15-LJ',
        name: 'LEGAL AND JUDICIAL SERVICE',
        groups: [
            { group_code: 'ATTY', group_name: 'Attorneys' },
            { group_code: 'GCC', group_name: 'Government Corporate Counsels' },
            {
                group_code: 'GI',
                group_name: 'Graft Investigation and Prosecution',
            },
            { group_code: 'JJ', group_name: 'Judges and Justices' },
            { group_code: 'JA', group_name: 'Judicial Administration' },
            { group_code: 'LAWE', group_name: 'Law Education' },
            { group_code: 'LR', group_name: 'Law Reform' },
            { group_code: 'LC', group_name: 'Legal Assistance' },
            { group_code: 'PE', group_name: 'Prosecution' },
            { group_code: 'PAT', group_name: 'Public Attorneys' },
            { group_code: 'SL', group_name: 'Solicitors' },
            { group_code: 'SP', group_name: 'Special Prosecution' },
            { group_code: 'SC', group_name: 'State Counsels' },
        ],
    },
    {
        occupational_service_code: '16-FR',
        name: 'FOREIGN RELATIONS SERVICE',
        groups: [
            { group_code: 'AS', group_name: 'Attaché Service' },
            { group_code: 'FAR', group_name: 'Foreign Affairs Research' },
            { group_code: 'FS', group_name: 'Foreign Service' },
            { group_code: 'FTS', group_name: 'Foreign Trade Service' },
        ],
    },
    {
        occupational_service_code: '17-MS',
        name: 'MISCELLANEOUS SERVICE',
        groups: [
            { group_code: 'BC', group_name: 'Barbering and Cosmetology' },
            { group_code: 'FOS', group_name: 'Food Service' },
            { group_code: 'LW', group_name: 'Laundry Working' },
            { group_code: 'LDS', group_name: 'Lodging Service' },
            { group_code: 'PTA', group_name: 'Park Administration' },
            { group_code: 'PO', group_name: 'Parking Operations' },
            { group_code: 'PK', group_name: 'Poundkeeping' },
        ],
    },
    {
        occupational_service_code: '18-ES',
        name: 'EXECUTIVE SERVICE',
        groups: [
            { group_code: 'CE', group_name: 'Chief Executive' },
            { group_code: 'CES', group_name: 'Chief Executive Support' },
            { group_code: 'OM', group_name: 'Operating Management' },
            { group_code: 'PM', group_name: 'Project Management' },
            { group_code: 'TMG', group_name: 'Top Management' },
        ],
    },
    {
        occupational_service_code: '19-LS',
        name: 'LEGISLATIVE SERVICE',
        groups: [{ group_code: 'CG', group_name: 'Congress' }],
    },
    {
        occupational_service_code: '20-CG',
        name: 'CORPORATE GOVERNANCE',
        groups: [
            { group_code: 'CGA', group_name: 'Corporate Governance Affairs' },
        ],
    },
];
